### ISSUE TITLE
Feature request: Generate Sprite2D

### ISSUE THREAD

**Issue by golddotasksquestions** [zarstensen/GodotAnnotate#3]
Hi, thank you very much for this plugin, it's super easy and intuitive to use, honestly very fun!

I think I would love to use it in future for prototyping as well as it seems so quick and easy to draw simple characters, items, environment things as placeholders. I could even imagine creating a whole game with this, but then the engine would do a lot of _draw() processing all the time. 
So I was thinking if it would be possible to add functionality to save the drawing as png and generate a texture which then gets the png assigned.

Thanks again!

**Comment by zarstensen** [comment]
Hi @golddotasksquestions, thanks again for the compliments and for the feature request.

I'm not sure this is still relevant since #6 removes almost all _draw related calls in the plugin and replaces them with Line2D nodes which are significantly faster.

If you have any other reason for this feature other than performance, or still feel the performance will be significantly improved by this feature, please say so!

Otherwise i will close this in a couple of days.

**Comment by golddotasksquestions** [comment]
Yes I have plenty of reason for this feature other than performance.

My biggest reason is how fun it is to use AnnotateCanvas node. It's so straight forward and intuitive to use, it would be awesome to use for so much more than just annotations. I honestly can very well imagine to create all the visuals for various games with just this node. Especially for jam games, this node would be super fun to use.

While I guess to some degree it would be possible to just use the node as it is so create game visuals, a texture would have the benefits of being very robust established resource and able to be used at various other places in the engine. I could use it as texture for AnimatedSprites, for TextureButtons, for TextureRects, as texture for 3D Materials, as texture in shaders ... the list goes on.

Also if you adding a CanvasItem shader to a Line2D has a totally different result compared to a texture. Currently it does not seem to be possible to add a shader to the AnnotationCanvas node, even though it is a 2D node. Well it is possible, the shader just won't have any effect.
