### ISSUE TITLE
Feature Request: Slider to adjust stroke step freuency/detail

### ISSUE THREAD

**Issue by golddotasksquestions** [zarstensen/GodotAnnotate#4]
As mentioned in the other Feature Request, I love how easy it is to do quick sketches and create placeholder graphics with this plugin, but they always look a bit choppy, due to the amounts of points used to draw the line. 

I looked through the script, trying to find where this frequency is set, but count not find it. Maybe you could expose this as a slider in the Inspector so people can draw smoother curves or even more angular designs if they want to?

Thank you again!

**Comment by zarstensen** [comment]
Hi @golddotasksquestions, thanks for the feature request.

The point frequency is actually controlled by the [MIN_POINT_DISTANCE](https://github.com/zarstensen/GodotAnnotate/blob/deedc0b0fb27c33a0e3e1d4a796d93bc6c139902/src/annotate_stroke.gd#L7C1-L7C32) constant, so it should be relatively simple to implement a way to adjust this value in a UI.

Does the choppiness you are referring to happen on sharp angles? If so, lowering this value will actually make this worse, as the draw_polyline function does not allow to control the joint drawing mode, and will instead default to sharp.

The a way of fixing this is by manually drawing the joints with draw_circle, but this is really slow due to the number of individual draw calls required.

An alternative method is by using a Line2D to draw the stroke, instead of utilizing the _draw function.

I will open a separate issue for fixing the line choppiness and keep this one open for the point freq slider feature request.

**Comment by zarstensen** [comment]
Adjustable minimum point distance was implemented in #6 and will be available in the next release.

**Comment by golddotasksquestions** [comment]
> Does the choppiness you are referring to happen on sharp angles?

with "choppiness" I was actually referring to the number of points, not the corners. Faster movements made it obvious the line from point to point is actually straight, so drawing a circle looked more like drawing a polygon (a circle with chopped off sides).

I did not mind the sharp angles on corners when drawing zig-zag lines. But without the sharp corners it's fine too. Line2D offers the ability to chose, which is nice of course.

**Comment by zarstensen** [comment]
The round joints will probably still diminish the obviousness of the number of points in a stroke, however it seems what you are observing is more related to the processing speed of the godot editor?
Point frequency is determined by distance to the previous point, and not an amount of time passing so faster movements should in theory not change the point density.
The only other thing that would control how often points are drawn is the fps of the editor, so if your editor is lagging a bit, the strokes will not be as smooth either.
